description: |
  Allows post-processing of input events based on the configuration

compatible: "zmk,input-configs"

child-binding:
  description: "A configuration for a given input device"

  properties:
    device:
      type: phandle
      required: true
    xy-swap:
      type: boolean
    x-invert:
      type: boolean
    y-invert:
      type: boolean
    scale-multiplier:
      type: int
      default: 1
    scale-divisor:
      type: int
      default: 1
    layer-toggle:
      type: int
      default: -1
      required: false
      description: The layer that should be toggled when the mouse is moved.
    layer-toggle-delay-ms:
      type: int
      default: 250
      required: false
      description: How many miliseconds of mouse activity are required before the layer is toggled on.
    layer-toggle-timeout-ms:
      type: int
      default: 250
      required: false
      description: How many miliseconds of mouse inactivity are required before the layer is toggled off again.
